/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AppUserService } from "../appUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AppUserCreateInput } from "./AppUserCreateInput";
import { AppUser } from "./AppUser";
import { AppUserFindManyArgs } from "./AppUserFindManyArgs";
import { AppUserWhereUniqueInput } from "./AppUserWhereUniqueInput";
import { AppUserUpdateInput } from "./AppUserUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";
import { HootFindManyArgs } from "../../hoot/base/HootFindManyArgs";
import { Hoot } from "../../hoot/base/Hoot";
import { HootWhereUniqueInput } from "../../hoot/base/HootWhereUniqueInput";
import { ReactionFindManyArgs } from "../../reaction/base/ReactionFindManyArgs";
import { Reaction } from "../../reaction/base/Reaction";
import { ReactionWhereUniqueInput } from "../../reaction/base/ReactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AppUserControllerBase {
  constructor(
    protected readonly service: AppUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppUser })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAppUser(
    @common.Body() data: AppUserCreateInput
  ): Promise<AppUser> {
    return await this.service.createAppUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AppUser] })
  @ApiNestedQuery(AppUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appUsers(@common.Req() request: Request): Promise<AppUser[]> {
    const args = plainToClass(AppUserFindManyArgs, request.query);
    return this.service.appUsers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appUser(
    @common.Param() params: AppUserWhereUniqueInput
  ): Promise<AppUser | null> {
    const result = await this.service.appUser({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAppUser(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() data: AppUserUpdateInput
  ): Promise<AppUser | null> {
    try {
      return await this.service.updateAppUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAppUser(
    @common.Param() params: AppUserWhereUniqueInput
  ): Promise<AppUser | null> {
    try {
      return await this.service.deleteAppUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comment",
    action: "read",
    possession: "any",
  })
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: AppUserWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,

        hoot: {
          select: {
            id: true,
          },
        },

        id: true,
        parentCommentId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async connectComments(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async updateComments(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async disconnectComments(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/hoots")
  @ApiNestedQuery(HootFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "read",
    possession: "any",
  })
  async findHoots(
    @common.Req() request: Request,
    @common.Param() params: AppUserWhereUniqueInput
  ): Promise<Hoot[]> {
    const query = plainToClass(HootFindManyArgs, request.query);
    const results = await this.service.findHoots(params.id, {
      ...query,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/hoots")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async connectHoots(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: HootWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hoots: {
        connect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/hoots")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async updateHoots(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: HootWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hoots: {
        set: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/hoots")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async disconnectHoots(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: HootWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hoots: {
        disconnect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reactions")
  @ApiNestedQuery(ReactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reaction",
    action: "read",
    possession: "any",
  })
  async findReactions(
    @common.Req() request: Request,
    @common.Param() params: AppUserWhereUniqueInput
  ): Promise<Reaction[]> {
    const query = plainToClass(ReactionFindManyArgs, request.query);
    const results = await this.service.findReactions(params.id, {
      ...query,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        hoot: {
          select: {
            id: true,
          },
        },

        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async connectReactions(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        connect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async updateReactions(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        set: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "update",
    possession: "any",
  })
  async disconnectReactions(
    @common.Param() params: AppUserWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        disconnect: body,
      },
    };
    await this.service.updateAppUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
