/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentUpdateManyWithoutAppUsersInput } from "./CommentUpdateManyWithoutAppUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { HootUpdateManyWithoutAppUsersInput } from "./HootUpdateManyWithoutAppUsersInput";
import { ReactionUpdateManyWithoutAppUsersInput } from "./ReactionUpdateManyWithoutAppUsersInput";

@InputType()
class AppUserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutAppUsersInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => HootUpdateManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => HootUpdateManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => HootUpdateManyWithoutAppUsersInput, {
    nullable: true,
  })
  hoots?: HootUpdateManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReactionUpdateManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => ReactionUpdateManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => ReactionUpdateManyWithoutAppUsersInput, {
    nullable: true,
  })
  reactions?: ReactionUpdateManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { AppUserUpdateInput as AppUserUpdateInput };
