/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HootService } from "../hoot.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HootCreateInput } from "./HootCreateInput";
import { Hoot } from "./Hoot";
import { HootFindManyArgs } from "./HootFindManyArgs";
import { HootWhereUniqueInput } from "./HootWhereUniqueInput";
import { HootUpdateInput } from "./HootUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";
import { ReactionFindManyArgs } from "../../reaction/base/ReactionFindManyArgs";
import { Reaction } from "../../reaction/base/Reaction";
import { ReactionWhereUniqueInput } from "../../reaction/base/ReactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HootControllerBase {
  constructor(
    protected readonly service: HootService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Hoot })
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHoot(@common.Body() data: HootCreateInput): Promise<Hoot> {
    return await this.service.createHoot({
      data: {
        ...data,

        appUser: data.appUser
          ? {
              connect: data.appUser,
            }
          : undefined,
      },
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Hoot] })
  @ApiNestedQuery(HootFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hoots(@common.Req() request: Request): Promise<Hoot[]> {
    const args = plainToClass(HootFindManyArgs, request.query);
    return this.service.hoots({
      ...args,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Hoot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hoot(
    @common.Param() params: HootWhereUniqueInput
  ): Promise<Hoot | null> {
    const result = await this.service.hoot({
      where: params,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Hoot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHoot(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() data: HootUpdateInput
  ): Promise<Hoot | null> {
    try {
      return await this.service.updateHoot({
        where: params,
        data: {
          ...data,

          appUser: data.appUser
            ? {
                connect: data.appUser,
              }
            : undefined,
        },
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Hoot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHoot(
    @common.Param() params: HootWhereUniqueInput
  ): Promise<Hoot | null> {
    try {
      return await this.service.deleteHoot({
        where: params,
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comment",
    action: "read",
    possession: "any",
  })
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: HootWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,

        hoot: {
          select: {
            id: true,
          },
        },

        id: true,
        parentCommentId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async connectComments(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async updateComments(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async disconnectComments(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reactions")
  @ApiNestedQuery(ReactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reaction",
    action: "read",
    possession: "any",
  })
  async findReactions(
    @common.Req() request: Request,
    @common.Param() params: HootWhereUniqueInput
  ): Promise<Reaction[]> {
    const query = plainToClass(ReactionFindManyArgs, request.query);
    const results = await this.service.findReactions(params.id, {
      ...query,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        hoot: {
          select: {
            id: true,
          },
        },

        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async connectReactions(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        connect: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async updateReactions(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        set: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reactions")
  @nestAccessControl.UseRoles({
    resource: "Hoot",
    action: "update",
    possession: "any",
  })
  async disconnectReactions(
    @common.Param() params: HootWhereUniqueInput,
    @common.Body() body: ReactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reactions: {
        disconnect: body,
      },
    };
    await this.service.updateHoot({
      where: params,
      data,
      select: { id: true },
    });
  }
}
